/* eslint-disable */
/* global WebImporter */

/**
 * Parser: hero-landing
 * Base block: hero
 * Source: https://www.wknd-trendsetters.site/case-studies
 * Selector: header.section.secondary-section
 * Generated: 2026-03-18
 *
 * Hero block structure (from library):
 *   1 column, 3 rows:
 *   Row 1: block name (auto-generated by createBlock)
 *   Row 2: [background image(s)] (optional)
 *   Row 3: [heading, subheading, CTA buttons]
 *
 * Source structure (case-studies): text-only hero
 *   H1 heading (.h1-heading), subheading paragraph (.subheading),
 *   CTA button (.button-group a.button). No images in hero section.
 *
 * Source structure (homepage): two-column grid layout
 *   Left column: h1, subheading, 2 CTA buttons
 *   Right column: grid of 3 cover images
 */
export default function parse(element, { document }) {
  // Extract images from source DOM (from captured DOM: .grid-layout img.cover-image)
  const images = Array.from(element.querySelectorAll('.grid-layout img.cover-image, img.cover-image'));

  // Extract heading (from captured DOM: h1, .h1-heading)
  const heading = element.querySelector('h1, .h1-heading');

  // Extract subheading (from captured DOM: .subheading, p.subheading)
  const subheading = element.querySelector('.subheading, p.subheading');

  // Extract description paragraphs (not subheading, not buttons)
  const descriptionParagraphs = Array.from(element.querySelectorAll('p')).filter((p) => {
    if (p === subheading) return false;
    if (p.closest('.button-group')) return false;
    if (p.classList.contains('subheading')) return false;
    const text = p.textContent.trim();
    return text.length > 0 && !p.querySelector('a.button');
  });

  // Extract CTA buttons (from captured DOM: .button-group a.button)
  const buttons = Array.from(element.querySelectorAll('.button-group a.button, a.button'));

  const cells = [];

  // Row 1 (after block name): all images in a single cell (optional - case-studies has no images)
  if (images.length > 0) {
    const imageCell = document.createElement('div');
    images.forEach((img) => imageCell.append(img));
    cells.push([imageCell]);
  }

  // Row 2 (after block name): heading + subheading + description + CTAs in a single cell
  const contentContainer = document.createElement('div');
  if (heading) contentContainer.append(heading);
  if (subheading) contentContainer.append(subheading);
  descriptionParagraphs.forEach((p) => contentContainer.append(p));
  buttons.forEach((btn) => {
    const p = document.createElement('p');
    p.append(btn);
    contentContainer.append(p);
  });
  cells.push([contentContainer]);

  const block = WebImporter.Blocks.createBlock(document, { name: 'hero-landing', cells });
  element.replaceWith(block);
}
