/* eslint-disable */
/* global WebImporter */

/**
 * Parser: hero-banner
 * Base block: hero
 * Source: https://www.wknd-trendsetters.site/
 * Selector: section.section.inverse-section
 * Generated: 2026-03-18
 *
 * Hero block structure (from library):
 *   1 column, 3 rows:
 *   Row 1: block name (auto-generated by createBlock)
 *   Row 2: [background image] (optional)
 *   Row 3: [heading, subheading, CTA button(s)]
 *
 * Source structure: Full-width dark overlay section with:
 *   - Background image (img.cover-image within .utility-position-relative)
 *   - H2 heading (.h1-heading class used for styling)
 *   - Subheading paragraph (p.subheading)
 *   - CTA button (.button-group a.button.inverse-button)
 */
export default function parse(element, { document }) {
  // Background image (from captured DOM: img.cover-image)
  const img = element.querySelector('img.cover-image');

  // Heading (from captured DOM: h2, .h1-heading)
  const heading = element.querySelector('h2, .h1-heading');

  // Description (from captured DOM: p.subheading, .card-body p.subheading)
  const description = element.querySelector('p.subheading, .card-body p.subheading');

  // CTA buttons (from captured DOM: .button-group a.button)
  const buttons = Array.from(element.querySelectorAll('.button-group a.button'));

  const cells = [];

  // Row 1: Background image
  if (img) {
    cells.push([img]);
  }

  // Row 2: Heading, description, CTA buttons
  const contentCell = [];
  if (heading) {
    const h2 = document.createElement('h2');
    h2.textContent = heading.textContent.trim();
    contentCell.push(h2);
  }
  if (description) {
    const p = document.createElement('p');
    p.textContent = description.textContent.trim();
    contentCell.push(p);
  }
  buttons.forEach((btn) => {
    const link = document.createElement('a');
    link.href = btn.getAttribute('href') || '#';
    link.textContent = btn.textContent.trim();
    const p = document.createElement('p');
    p.append(link);
    contentCell.push(p);
  });

  if (contentCell.length > 0) {
    cells.push(contentCell);
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'hero-banner', cells });
  element.replaceWith(block);
}
